name: CI-Jakob

on:
  push:
    branches: ["main"]

  pull_request:
    branches:
      - main


jobs:
  formatting:
    name: Stylecheck code with Ruff
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Setup Python
        run: uv python install

      - name: Install project
        run: uv sync --frozen

      - name: Run Ruff
        run: uvx ruff check . --output-format=github

  test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:

          enable-cache: true

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --frozen

      - name: Run tests
        run: uv run pytest
